-- Active: 1694385916137@@127.0.0.1@5432@skatepark
-- Generated by the database client, not guaranteed complete.
CREATE TABLE skaters(
    "id" SERIAL NOT NULL,
    "email" character varying(50) NOT NULL,
    "nombre" character varying(25) NOT NULL,
    "password" character varying(25) NOT NULL,
    "anos_experiencia" integer NOT NULL,
    "especialidad" character varying(50) NOT NULL,
    "foto" character varying(255) NOT NULL,
    "estado" boolean NOT NULL DEFAULT false,
    "roles" character varying(50) DEFAULT 'USER'::character varying,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX skaters_email_key ON "skaters" USING btree (email);